### ISSUE TITLE
Can't bind django project/app.

### ISSUE THREAD

**Issue by pandabuilder** [amol-mandhane/htmlPy#7]
Can't seem to bind a django app + project to htmlpy, and the docs are missing a working example of this. Tried binding get_wsgi_application() from django.core.wsgi to htmlPy.AppGUI instance to no avail.

**Comment by amol-mandhane** [comment]
You don't have to bind anything while using htmlPy with django. The only difference between running django server vs running django + htmlPy application is that you have to run htmlPy driver file instead of server command.

Add this in the driver file
`import os`
`os.environ.setdefault("DJANGO_SETTINGS_MODULE", "<project_name>.settings")`

Docs have example on how to create driver file. I intend a add a repo of django + htmlPy sample application.
